import 'package:flutter/material.dart';

import '../models/transactions.dart';
import './transaction_item.dart';

class TransactionList extends StatelessWidget {
  // const TransactionList({Key? key}) : super(key: key);
  final List<Transaction> transactions;
  final Function deleteTx;

  const TransactionList(this.transactions, this.deleteTx);

  @override
  Widget build(BuildContext context) {
    print("TransactionList build");

    return Container(
      height: 300,
      child: transactions.isEmpty
          ? LayoutBuilder(builder: (context, constraints) {
              return Column(
                children: [
                  Text(
                    "No transactions added yet !",
                    style: Theme.of(context).textTheme.headline6,
                  ),
                  const SizedBox(
                    height: 10,
                  ),
                  Container(
                      height: constraints.maxHeight * 0.6,
                      child: Image.asset(
                        "assets/images/waiting.png",
                        fit: BoxFit.cover,
                      )),
                ],
              );
            })
          // : ListView.builder(
          //     itemBuilder: (context, index) {
          //       return
          : ListView(
          children: transactions.map((e) => TransactionItem(transaction: e, deleteTx: deleteTx, key: ValueKey(e.id),)).toList(),
                    //   Card(child:
                    // Row(
                    //   children: [
                    //     Container(
                    //       margin: const EdgeInsets.symmetric(vertical: 10, horizontal: 15),
                    //       decoration: BoxDecoration(border: Border.all(
                    //           width: 2,
                    //           color: Theme.of(context).primaryColor,
                    //       )),
                    //       padding: const EdgeInsets.all(10),
                    //       child: Text(
                    //         "\$${transactions[index].amount.toStringAsFixed(2)}",
                    //         style: TextStyle(
                    //             fontWeight: FontWeight.bold,
                    //             fontSize: 20,
                    //             color: Theme.of(context).primaryColor
                    //         ),
                    //       ),
                    //     ),
                    //     Column(
                    //       mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    //       crossAxisAlignment: CrossAxisAlignment.start,
                    //       children: [
                    //         Text(
                    //             // style: const TextStyle(
                    //             //     fontSize: 16,
                    //             //     fontWeight: FontWeight.bold
                    //             // ),
                    //             style: Theme.of(context).textTheme.headline6,
                    //             transactions[index].title
                    //         ),
                    //         Text(
                    //           DateFormat().add_yMMMMd().format(transactions[index].date),
                    //           style: const TextStyle(
                    //               fontSize: 13,
                    //               color: Colors.grey
                    //           ),
                    //
                    //         ),
                    //       ],
                    //     )
                    //   ],
                    // ),
                    // );

                    // TransactionItem(transaction: transactions[index], deleteTx: deleteTx, key: ValueKey(transactions[index].id),);
                    ),
                   );
     // );
    //UniqueKey() is generated by flutter so every time it changes with a new one, so we could use ValueKey() instead that is unique to every list item i have and you pass this key by your hand
    }
             // itemCount: transactions.length,
          //  ),

   // );
  }



